name: svastikkka
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter=1.0.0
  - numpy=1.21.2
  - pandas=1.3.3
  # - mysql-connector-python=8.0.26
  - minio=7.1.2
  - twine=3.4.2
  - beautifulsoup4=4.10.0
  - scikit-learn=0.24.2
  - seaborn=0.11.2
  - matplotlib=3.4.3
  - nltk=3.6.3
